---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"
        
    - name: Actualizar todos los paquetes
      yum:
        name: '*'
        state: latest

    - name: Limpiar caché de YUM
      yum:
        name: '*'
        state: latest
        update_only: yes
        autoremove: yes

    - name: Reiniciar el sistema si es necesario
      reboot:
        msg: "Reiniciando el sistema después de la actualización."
        test: yes
